# Definition
type StorageItemRecord {
  id: ID!

  item: StorageItem!

  quantity: Int!
  description: String
  createdAt: String!
  updatedAt: String!
}
# Queries
extend type Query {
  ListStorageItemRecords: [StorageItemRecord!]!
  GetStorageItemRecord(id: Int!): StorageItemRecord!
}
# Mutations
union StorageItemRecordMutationResponse = StorageItemRecord | Error
input StorageItemRecordMutationInput {
  itemId: Int!
  quantity: Int!
  description: String
}
extend type Mutation {
  CreateStorageItemRecord(
    input: StorageItemRecordMutationInput!
  ): StorageItemRecordMutationResponse!
  UpdateStorageItemRecord(
    id: Int!
    input: StorageItemRecordMutationInput!
  ): StorageItemRecordMutationResponse!
  DeleteStorageItemRecord(id: Int!): StorageItemRecordMutationResponse!
}
